#!/bin/bash

if [ ! -d "html" ]; then
    mkdir html
fi

if [ $# -eq 0 ]
then
    xml=xml/*.xml

    for file in ${xml}
    do
	html=html/${file#xml/}
	html=${html%.xml}.html
	xsltproc xml2html.xsl ${file} > ${html} && echo "Le fichier \"$html\" a ete cree"
    done
else
    echo "ok";
fi
